name: Multistage Build

on: 
  push:
    branches: ["*"]
  pull_request: 
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Dockerfile image for amd64
        run: docker buildx build --platform linux/amd64 -t miros12/http_server:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker buildx build --platform linux/arm64 -t miros12/http_server:arm64 --push .
      
      - name: Create manifest
        run: docker manifest create miros12/http_server --amend miros12/http_server:amd64 --amend miros12/http_server:arm64

      - name: Push manifest to Docker Hub
        run: docker manifest push miros12/http_server

