name: Tests

on: 
  push:
    branches: ["branchAutoTest"]
  pull_request: 
    branches: ["branchAutoTest"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev automake autoconf
          
      - name: Install GCC 11
        run: |
          sudo apt-get install -y gcc-11 g++-11
          
      - name: Set GCC 11 as default
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

      - name: Clean build
        run: make clean
      
      - name: Build
        run: |
          autoreconf -i
          make

      - name: Tests
        run: make check

